/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface ISwapHelperInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "fulfillQuote"
      | "fulfillSwap"
      | "requestQuote"
      | "requestSwap"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "fulfillQuote",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "fulfillSwap",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestQuote",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "requestSwap",
    values: [AddressLike, AddressLike, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "fulfillQuote",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fulfillSwap",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestQuote",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestSwap",
    data: BytesLike
  ): Result;
}

export interface ISwapHelper extends BaseContract {
  connect(runner?: ContractRunner | null): ISwapHelper;
  waitForDeployment(): Promise<this>;

  interface: ISwapHelperInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  fulfillQuote: TypedContractMethod<[], [void], "nonpayable">;

  fulfillSwap: TypedContractMethod<[], [void], "nonpayable">;

  requestQuote: TypedContractMethod<
    [src: AddressLike, dst: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  requestSwap: TypedContractMethod<
    [
      src: AddressLike,
      dst: AddressLike,
      amount: BigNumberish,
      slippage: BigNumberish
    ],
    [void],
    "payable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "fulfillQuote"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "fulfillSwap"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requestQuote"
  ): TypedContractMethod<
    [src: AddressLike, dst: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "requestSwap"
  ): TypedContractMethod<
    [
      src: AddressLike,
      dst: AddressLike,
      amount: BigNumberish,
      slippage: BigNumberish
    ],
    [void],
    "payable"
  >;

  filters: {};
}
