/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as lzEndpointMockSol from "./LZEndpointMock.sol";
export type { lzEndpointMockSol };
import type * as stargateMockSol from "./StargateMock.sol";
export type { stargateMockSol };
export type { BridgeMock } from "./BridgeMock";
