/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IVaultTokenReward,
  IVaultTokenRewardInterface,
} from "../../../../contracts/integrations/pika/IVaultTokenReward";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "earned",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getReward",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IVaultTokenReward__factory {
  static readonly abi = _abi;
  static createInterface(): IVaultTokenRewardInterface {
    return new Interface(_abi) as IVaultTokenRewardInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IVaultTokenReward {
    return new Contract(address, _abi, runner) as unknown as IVaultTokenReward;
  }
}
