/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IBaseStrategy,
  IBaseStrategyInterface,
} from "../../../contracts/interfaces/IBaseStrategy";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_debtOutstanding",
        type: "uint256",
      },
    ],
    name: "adjustPosition",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "estimatedTotalAssets",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_newStrategy",
        type: "address",
      },
    ],
    name: "migrate",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "withdraw",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IBaseStrategy__factory {
  static readonly abi = _abi;
  static createInterface(): IBaseStrategyInterface {
    return new Interface(_abi) as IBaseStrategyInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IBaseStrategy {
    return new Contract(address, _abi, runner) as unknown as IBaseStrategy;
  }
}
