/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface IExchangeInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "scaleFromUnderlying"
      | "scaleToUnderlying"
      | "swapFromUnderlying"
      | "updateMintingStats"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "scaleFromUnderlying",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "scaleToUnderlying",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "swapFromUnderlying",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateMintingStats",
    values: [BigNumberish[]]
  ): string;

  decodeFunctionResult(
    functionFragment: "scaleFromUnderlying",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "scaleToUnderlying",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapFromUnderlying",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateMintingStats",
    data: BytesLike
  ): Result;
}

export interface IExchange extends BaseContract {
  connect(runner?: ContractRunner | null): IExchange;
  waitForDeployment(): Promise<this>;

  interface: IExchangeInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  scaleFromUnderlying: TypedContractMethod<
    [amount: BigNumberish],
    [bigint],
    "view"
  >;

  scaleToUnderlying: TypedContractMethod<
    [amount: BigNumberish],
    [bigint],
    "view"
  >;

  swapFromUnderlying: TypedContractMethod<
    [amountIn: BigNumberish, to: AddressLike],
    [bigint],
    "nonpayable"
  >;

  updateMintingStats: TypedContractMethod<
    [delta: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "scaleFromUnderlying"
  ): TypedContractMethod<[amount: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "scaleToUnderlying"
  ): TypedContractMethod<[amount: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "swapFromUnderlying"
  ): TypedContractMethod<
    [amountIn: BigNumberish, to: AddressLike],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateMintingStats"
  ): TypedContractMethod<[delta: BigNumberish[]], [void], "nonpayable">;

  filters: {};
}
