/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IUSDCMock,
  IUSDCMockInterface,
} from "../../../../../contracts/mock/crossChain/StargateMock.sol/IUSDCMock";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_amount",
        type: "uint256",
      },
    ],
    name: "burn",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_amount",
        type: "uint256",
      },
    ],
    name: "mint",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IUSDCMock__factory {
  static readonly abi = _abi;
  static createInterface(): IUSDCMockInterface {
    return new Interface(_abi) as IUSDCMockInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IUSDCMock {
    return new Contract(address, _abi, runner) as unknown as IUSDCMock;
  }
}
